# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_player_widget.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddPlayer(object):
    def setupUi(self, AddPlayer):
        AddPlayer.setObjectName("AddPlayer")
        AddPlayer.resize(1024, 768)
        self.label = QtWidgets.QLabel(AddPlayer)
        self.label.setGeometry(QtCore.QRect(6, 6, 1011, 45))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(AddPlayer)
        self.label_2.setGeometry(QtCore.QRect(64, 100, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(AddPlayer)
        self.label_3.setGeometry(QtCore.QRect(66, 138, 108, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(AddPlayer)
        self.label_4.setGeometry(QtCore.QRect(88, 176, 86, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(AddPlayer)
        self.label_5.setGeometry(QtCore.QRect(61, 214, 113, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(AddPlayer)
        self.label_6.setGeometry(QtCore.QRect(126, 252, 48, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(AddPlayer)
        self.label_7.setGeometry(QtCore.QRect(63, 290, 111, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.firstname_edit = QtWidgets.QLineEdit(AddPlayer)
        self.firstname_edit.setGeometry(QtCore.QRect(180, 100, 291, 32))
        self.firstname_edit.setObjectName("firstname_edit")
        self.last_name_edit = QtWidgets.QLineEdit(AddPlayer)
        self.last_name_edit.setGeometry(QtCore.QRect(180, 138, 291, 32))
        self.last_name_edit.setObjectName("last_name_edit")
        self.ranking_edit = QtWidgets.QLineEdit(AddPlayer)
        self.ranking_edit.setGeometry(QtCore.QRect(180, 176, 291, 32))
        self.ranking_edit.setObjectName("ranking_edit")
        self.nationality_edit = QtWidgets.QLineEdit(AddPlayer)
        self.nationality_edit.setGeometry(QtCore.QRect(180, 214, 291, 32))
        self.nationality_edit.setObjectName("nationality_edit")
        self.title_edit = QtWidgets.QLineEdit(AddPlayer)
        self.title_edit.setGeometry(QtCore.QRect(180, 252, 291, 32))
        self.title_edit.setObjectName("title_edit")
        self.chessclub_edit = QtWidgets.QLineEdit(AddPlayer)
        self.chessclub_edit.setGeometry(QtCore.QRect(180, 290, 291, 32))
        self.chessclub_edit.setObjectName("chessclub_edit")
        self.add_player_button = QtWidgets.QPushButton(AddPlayer)
        self.add_player_button.setGeometry(QtCore.QRect(590, 100, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.add_player_button.setFont(font)
        self.add_player_button.setObjectName("add_player_button")

        self.retranslateUi(AddPlayer)
        QtCore.QMetaObject.connectSlotsByName(AddPlayer)

    def retranslateUi(self, AddPlayer):
        _translate = QtCore.QCoreApplication.translate
        AddPlayer.setWindowTitle(_translate("AddPlayer", "Form"))
        self.label.setText(_translate("AddPlayer", "Add new player"))
        self.label_2.setText(_translate("AddPlayer", "First name:"))
        self.label_3.setText(_translate("AddPlayer", "Last name:"))
        self.label_4.setText(_translate("AddPlayer", "Ranking:"))
        self.label_5.setText(_translate("AddPlayer", "Nationality:"))
        self.label_6.setText(_translate("AddPlayer", "Title:"))
        self.label_7.setText(_translate("AddPlayer", "Chess club:"))
        self.add_player_button.setText(_translate("AddPlayer", "Add player"))
